project_id = "bavzbktxnsbzpsenvuzc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false

[realtime]
enabled = true

[studio]
enabled = true
api_url = "http://127.0.0.1:54321"

[analytics]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = false
